### PR TITLE
new_CO2

### PR DESCRIPTION
**Pull request by dschlaep**
I created this pull request so that I can comment.

### CODE REVIEW

**Comment by dschlaep** [comment]
Commenting on commit 21eda7cc06ff2733ec6ddc81fae6dfd24be1eb3c

- Function `do_OneSite` (file 'Simulation_Run.R'): lines 1547-1567
    * This function attaches now a new package `library(stringr)`. This call changes the R landscape for the user -- very poor behavior for a package (more information, for instance, here [The R landscape](http://r-pkgs.had.co.nz/r.html#r-differences)). Please fix.

    * Multiple times the codes needs now information on the different part of a scenario name (see issue #113). I enhanced the code so that the object 'sim_scens' now offers such information. Particularly, for the use in `do_OneSite` lines 1555-1564: you should now use `delta <- sim_scens[["df"]][sc - 1, "Delta_yrs"]` and `RCP <- sim_scens[["df"]][sc - 1, "ConcScen"]` (which also eliminates the need for the additional package 'stringr')

    * The code only sets `rSOILWAT2::swCarbon_Delta(swRunScenariosData[[sc]])` if `sc > 1`. Shouldn't it be set to its default value if `sc == 1` for safety purposes?

**Comment by Zachary-Kramer** [comment]
> This function attaches now a new package library(stringr). This call changes the R landscape for the user -- very poor behavior for a package (more information, for instance, here The R landscape). Please fix.

Noted

> Multiple times the codes needs now information on the different part of a scenario name (see issue #113). I enhanced the code so that the object 'sim_scens' now offers such information.

I will use your implementation shortly, it seems much cleaner

> The code only sets rSOILWAT2::swCarbon_Delta(swRunScenariosData[[sc]]) if sc > 1. Shouldn't it be set to its default value if sc == 1 for safety purposes?

When sc == 1, the delta will always be the default of the swCarbon class, which is 0. I don't see any way for scenario 1 to ever have a delta other than the default, as the value is only changed when sc > 1, and scenario 1 is only hit again when another site is run, but then there is a new instance of the swCarbon class. Is there a safety concern that I'm missing?

**Comment by dschlaep** [comment]
Great thanks. Sounds good -- sorry, I should have checked the prototype.

**Comment by Zachary-Kramer** [comment]
@dschlaep This code is now ready for a full review

**Comment by Zachary-Kramer** [comment]
It seems that tests\test_data\Test4_AllOverallAggregations_snow\1_Data_SWInput\experimental + treatment need to be updated to match what was changed in the normal input data

**Comment by dschlaep** [comment]
> should CO2 be enabled or disabled for test of 'Test4_AllOverallAggregations_snow'?

Please disable CO2 so that it produced old behavior and compares correctly to previous output.

However, we should add CO2-specific unit tests.

**Comment by dschlaep** [comment]
I looked at the code and it seems fine, but I cannot really test it without a test project to play with.

**Comment by dschlaep** [comment]
How do I set up a rSFSW2 project with multiple CO2-scenarios? Where do I put the CO2-data so that the different files are being read in during the different SOILWAT2 runs?

The experimental/design treatment csv input files do have appropriate fields including the specify different `CO2_Scenario`s: 
> UseCO2BiomassMultiplier,UseCO2WUEMultiplier,CO2_Scenario

and the default input folder `SoilWat2_defaults` gained a file `Input/carbon.in`.

What do I do if I have `carbon_rcp45_gcmX1.in`, `carbon_rcp85_gcmX1.in`, `carbon_rcp45_gcmX2.in`, ...?

The field `CO2_Scenario` causes only to pass its value to the rSOILWAT2 S4 slot:
`rSOILWAT2::swCarbon_Scenario(swRunScenariosData[[sc]]) <- as.character(i_sw_input_treatments$CO2_Scenario)` which in turn is passed to SOILWAT2 code. If SOILWAT2 doesn't find that scenario tag in the available `carbon.in` file, then it doesn't work. And it seems this doesn't work since one one `carbon.in` file can be functional in the default input folder `SoilWat2_defaults`?

**Comment by dschlaep** [comment]
Maybe create a new sub-folder, e.g,  `1_Data_SWInput/treatments/tr_carbon/` from where different `carbon_X.in` files are stored and made available to the runs? As we currently do, e.g., for `soils.in` by folder  `1_Data_SWInput/treatments/tr_soilsin/`

**Comment by Zachary-Kramer** [comment]
The intended functionality is to have a single carbon.in file that holds all scenarios. We decided on this because at the time we didn't have many scenarios and still aren't expecting many more to come. This file holds scenarios by name. Currently, there's just a generic "RCP85" scenario. You could add "RCP45_GCMx1" and x2 to carbon.in following the same pattern (year 0 is the scenario name, all values come after). The name itself is only used when comparing against the given scenario name in the experimental design or siteparam.in, so once you add these values you just need to reference the scenario in the experimental (CO2_Scenario).

We could take the multiple files approach, but I don't find it necessary at the moment

**Comment by dschlaep** [comment]
A `carbon.in` file with multiple scenarios would look like below?

> 0             RCP85_x1
> 2010	389.32416
> 2011	391.63801
> 2012	394.00866
> 2013	396.46384
> 2014	399.00402
> 
> 0             RCP85_x2
> 2010	388
> 2011	390
> 2012	392
> 2013	394
> 2014	396
> 
> 
> 0             RCP45_x
> 2010	389
> 2011	390
> 2012	393
> 2013	394
> 2014	398
> ...

**Comment by Zachary-Kramer** [comment]
Yes. I haven't tested finding a scenario past the first place (e.g. in this example I haven't tested finding RCP85_x2), so let me know if something seems wrong.

**Comment by dschlaep** [comment]
Ok, I run some tests with `SOILWAT2/testing/`. The c code is capable to find the correct CO2 concentration values of a requested scenario that is made available after other scenario data. However, the setup is very sensitive to input errors, i.e., the simulation runs and produces output whatever the file `carbon.in` contains: see issue https://github.com/Burke-Lauenroth-Lab/SOILWAT2/issues/62 where I suggest that the code errors out if the CO2-concentration is not as expected.

**Comment by dschlaep** [comment]
- I don't understand what is meant with the comment on line 894-895 in function `do_OneSite` in file `Simulation_Run.R` of commit: "CO2 effects rely on the information of the current scenario, so the extraction of its Lookup data doesn't occur until now"

- The current code is such that yearly CO2 values are only checked if `sw_input_experimentals_use["LookupCarbonScenarios"]` is `TRUE`. See issue https://github.com/Burke-Lauenroth-Lab/rSOILWAT2/issues/75. Also the checks are coded very inefficiently with a for-loop instead of vectorized and I cannot see what the purpose of the checks `ppm_value < 0.1 && ppm_value > -0.1` are. Carbon dioxide concentration values must be non-negative real numbers, i.e., (with the current setup without year-columns)
```
ids_years <- delta_yr + isim_time[["useyrs"]]
ppm_values <- tr_input_CarbonScenario[ids_years, scenario_index]
ids_bad <- is.na(ppm_values) | ppm_values <= SFSW2_glovars[["tol"]]
if (any(ids_bad)) {
  ...
}
```
But again, I believe this should be a method of the carbon class in `rSOILWAT2`

**Comment by Zachary-Kramer** [comment]
"CO2 effects rely on the information of the current scenario, so the extraction of its Lookup data doesn't occur until now" means:
1. The extraction of ppm data needs to happen after the scenario is saved to swRunScenariosData, which is on line 871 `swRunScenariosData[[sc]] <- swRunScenariosData[[1]]`
2. The extraction needs the following information from each scenario: name, delta year

Number two is accessible earlier on in the code by recreating the for loop that it is currently in (I believe), but number one is not accessible until this for loop, which perhaps should be better emphasized in the comment.

> The current code is such that yearly CO2 values are only checked if sw_input_experimentals_use["LookupCarbonScenarios"] is TRUE

Yes. Is this an issue? There will not always be ppm data available for a scenario (e.g. RCP45), so if a user opted to disable CO2 effects instead of overriding the scenario, we should not check the CO2 values.

> ppm_value < 0.1 && ppm_value > -0.1
This was meant to check if the year had a ppm value of 0, since that is the default value and is equivalent to having missing data. Obviously, we cannot have negative values either, so <= 0 is better in hindsight. I was hesitant to define what invalid ppm values are (e.g. should we count a very small value like 2 as invalid?), so I kept it simple.

> But again, I believe this should be a method of the carbon class in rSOILWAT2

Which part? The validation or the entire look up?

**Comment by Zachary-Kramer** [comment]
Any idea why appveyor is passing but travis-ci is not? When I run devtools::test() locally it fails with the same tests as travis-ci. 

The project is failing because something is calling SFSW2_read_csv with an empty file path.

**Comment by Zachary-Kramer** [comment]
The pull request was failing for multiple reasons:

1. The description file and other input data needed to be updated
2. The "Default" scenario crashes in SOILWAT2, because the values are of type integer while SOILWAT2 requires numeric

I fixed both issues. Now, the tests are failing for another reason and because the aggregations are different. See my attached run of `devtools::test()`

**Comment by Zachary-Kramer** [comment]
I am concerned that the appveyor build was passing. It ran testthat.R for 20s and had no issues. It should have been impossible to successfully run a project, because I just now made the builds use the CO2 branch of rSOILWAT2. Travis-ci was failing as expected under the circumstances, but appveyor somehow passed. @dschlaep do you know why this might be possible?

**Comment by dschlaep** [comment]
I agree it is worrisome that appveyor-ci checks pass.

appveyor-ci doesn't provide much output of the unit tests except
> test_check("rSFSW2")
testthat results ================================================================
OK: 2495 SKIPPED: 3 FAILED: 0
> 

On travis-ci, the unit tests are run in an environment with `NOT_CRAN = 'true'` and `TRAVIS = 'true'` --> hence, the unit tests in `tests/testthat/test_projects.R` (which are skipped on `cran`) are run (and fail).

It might be that appveyor-ci sets the cran flag and then skips the 'test_project' unit tests?

**Pull request merged**
